AWSTemplateFormatVersion: 2010-09-09
Description: Basic EC2 Instance.


Resources:
  DevEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0715c1897453cabd1
      InstanceType: t2.micro
      KeyName: hk-key1
      SecurityGroups:
        - default
