AWSTemplateFormatVersion: 2010-09-09
Description: KeyName Parameter demo

Parameters:
  KeyPairName:
    Type: String
    Description: Name of the EC2 Key Pair

  AMIId:
    Type: String
    Description: ID of the Amazon Machine Image (AMI)

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyPairName
      ImageId: !Ref AMIId
      # Add more properties as needed for your instance

Outputs:
  InstanceId:
    Value: !Ref MyEC2Instance
    Description: ID of the created EC2 instance
