AWSTemplateFormatVersion: '2010-09-09'
Resources:
  HKGlueServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Glue_Full_Access_test1
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
        - arn:aws:iam::aws:policy/AWSGlueConsoleFullAccess
        - arn:aws:iam::aws:policy/AWSLakeFormationDataAdmin

# Add role to Datalake administrators
  SampleDataLakeSettings:
    Type: AWS::LakeFormation::DataLakeSettings
    Properties:
      Admins:
        - DataLakePrincipalIdentifier: !GetAtt HKGlueServiceRole.Arn


